bibliography: ''
css_file: ''
extra_args:
- --wrap=preserve
- --pdf-engine=xelatex
- -V
- documentclass=bxjsarticle
- -V
- classoption=pandoc
- -V
- fontsize=10pt
- -V
- geometry:top=20mm,bottom=20mm,left=15mm,right=15mm,footskip=25pt
- --from
- markdown+hard_line_breaks
lua_filter: ''
merge_files: true
output_filename: ''
output_format: pdf
template: ''
use_custom_filename: false
