output_format: pdf
extra_args:
  - --wrap=preserve
  - --pdf-engine=xelatex
  - -V
  - documentclass=bxjsarticle
  - -V
  - classoption=pandoc
  - --from
  - markdown+hard_line_breaks
lua_filter: ""
template: ""
css_file: ""
bibliography: ""
merge_files: true
use_custom_filename: false
output_filename: ""
metadata: {} 